import type { Metadata } from "next";
import "./globals.css";
import clsx from "clsx";
import Providers from "@/providers";
import { Dosis } from "next/font/google";

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={clsx(
          "antialiased",
          "bg-white dark:bg-gray-950",
          dosis.variable,
          "font-dosis"
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
